version: '3'

services:
  fenix:
    container_name: khadas-fenix
    build:
     context: .
     dockerfile: Dockerfile
    tty: true
    stdin_open: true
    privileged: true
    volumes:
      - ${PWD}:/fenix
